version: 2

models:

  - name: int_sales_unified
    description: "Intermediate unified sales model combining Shopify and Walmart transactions."

  - name: int_customer_channel_usage
    description: "Intermediate model counting distinct channels per customer."
    columns:
      - name: customer_id
        tests:
          - not_null

      - name: channels_used
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 1"

  - name: int_product_pairs
    description: "Intermediate model identifying product pairs purchased by the same customers."
    columns:
      - name: product_1
        tests:
          - not_null

      - name: product_2
        tests:
          - not_null

      - name: times_bought_together
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 1"
